services:
  - type: web
    name: smashup.games
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: CLIENT_ORIGIN
        sync: false
